name: backend
services:

  db:
    container_name: db
    image: mysql:8
    restart: no
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changememaybe
      MYSQL_DATABASE: backend
      MYSQL_USER: backend
      MYSQL_PASSWORD: changeme
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
    command:
      - "--secure-file-priv="
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"