services:

  db:
    image: mysql:8
    restart: no
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changememaybe
      MYSQL_DATABASE: backend
      MYSQL_USER: backend
      MYSQL_PASSWORD: changeme
      OPT_LOCAL_INFILE: 1
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
      - "./db/01.cnf:/etc/mysql/conf.d/01.cnf"
#      - "../static/LoanStats_securev1_2017Q4.first-10-rows.csv:/docker-entrypoint-initdb.d/data.csv"
    command:
      - "--local-infile=1"
      - "--secure-file-priv=/docker-entrypoint-initdb.d"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"